# Site settings
title: Lakes-and-Rivers.com
author: Mothwave
 name: Ricky Lara-Monge
 description: Focusing on why we need Lakes and Rivers

---
# a comment 
example_key: example value
---
---
# a comment 
example_key: example value
---

# Build settings
remote_theme: jekyll/Cayman
