# Site settings
title: Lakes-and-Rivers.com
author: Mothwave
 name: Ricky Lara-Monge
 description: Focusing on why we need Lakes and Rivers

---
# a comment 
example_key: 7
---
---
# a comment 
example_key: 8
---

# Build settings
gem "jekyll-theme-basically-basic"
theme: jekyll-theme-basically-basic
bundle install
